INC_LIB_DIR  += -I$(SDK_ROOT)/components/drivers/indev/device

ifeq ($(CONFIG_INDEV_TOUCHPAD_SIM),y)
SOURCE_LIB_C += $(SDK_ROOT)/components/drivers/indev/device/indev_touchpad_sim.c
endif

ifeq ($(CONFIG_INDEV_FT6336U),y)
SOURCE_LIB_C += $(SDK_ROOT)/components/drivers/indev/device/indev_ft6336u.c
endif
