INC_LIB_DIR  += -I$(SDK_ROOT)/components/drivers/usb2otg/functions/uvc_camera

SOURCE_LIB_C += $(SDK_ROOT)/components/drivers/usb2otg/functions/uvc_camera/uvc_camera.c
SOURCE_LIB_C += $(SDK_ROOT)/components/drivers/usb2otg/functions/uvc_camera/uvc_camera_ep0.c
