include $(LVGL_DIR)/lvgl/porting/Makefile
include $(LVGL_DIR)/lvgl/src/Makefile

INC_LIB_DIR += -I$(LVGL_DIR)/lvgl
INC_LIB_DIR += -I$(LVGL_DIR)/lvgl/src
INC_LIB_DIR += -I$(LVGL_DIR)/lvgl/porting

PUBLIC_LIB_H +=  $(LVGL_DIR)/lvgl/lv_conf.h
PUBLIC_LIB_H +=  $(LVGL_DIR)/lvgl/lvgl.h
