INC_LIB_DIR  += -I$(SDK_ROOT)/components/drivers/usb2otg/functions/usb_sink_lpbk

SOURCE_LIB_C += $(SDK_ROOT)/components/drivers/usb2otg/functions/usb_sink_lpbk/usb_sink_lpbk.c
SOURCE_LIB_C += $(SDK_ROOT)/components/drivers/usb2otg/functions/usb_sink_lpbk/usb_sink_lpbk_ep0.c
