#ifndef _ISP_REG_OFFSET_H_
#define _ISP_REG_OFFSET_H_

// Registers from ISP_CORE block

#define mmISP_CORE_VI_ID                                0x0000
#define mmISP_CORE_VI_CCL                               0x0004
#define mmISP_CORE_VI_ICCL                              0x0008
#define mmISP_CORE_VI_IRCL                              0x000C
#define mmISP_CORE_VI_DPCL                              0x0010
#define mmISP_CORE_VI_CFG_UPD                           0x0014
#define mmISP_CORE_RMC_LSC_CTRL                         0x0080
#define mmISP_CORE_RMC_LSC_R_START                      0x0084
#define mmISP_CORE_RMC_LSC_R_DAT                        0x0088
#define mmISP_CORE_RMC_LSC_GR_START                     0x008C
#define mmISP_CORE_RMC_LSC_GR_DAT                       0x0090
#define mmISP_CORE_RMC_LSC_B_START                      0x0094
#define mmISP_CORE_RMC_LSC_B_DAT                        0x0098
#define mmISP_CORE_RMC_LSC_GB_START                     0x009C
#define mmISP_CORE_RMC_LSC_GB_DAT                       0x00A0
#define mmISP_CORE_RMC_DPC_BP_CTRL                      0x00A4
#define mmISP_CORE_RMC_DPC_BP_NUM                       0x00A8
#define mmISP_CORE_RMC_DPC_BP_START                     0x00AC
#define mmISP_CORE_RMC_DPC_BP_DAT                       0x00B0
#define mmISP_CORE_ISP_CTRL                             0x0400
#define mmISP_CORE_ISP_ACQ_PROP                         0x0404
#define mmISP_CORE_ISP_ACQ_H_OFFS                       0x0408
#define mmISP_CORE_ISP_ACQ_V_OFFS                       0x040C
#define mmISP_CORE_ISP_ACQ_H_SIZE                       0x0410
#define mmISP_CORE_ISP_ACQ_V_SIZE                       0x0414
#define mmISP_CORE_ISP_ACQ_NR_FRAMES                    0x0418
#define mmISP_CORE_ISP_GAMMA_DX_LO                      0x041C
#define mmISP_CORE_ISP_GAMMA_DX_HI                      0x0420
#define mmISP_CORE_ISP_GAMMA_R_Y_0                      0x0424
#define mmISP_CORE_ISP_GAMMA_R_Y_1                      0x0428
#define mmISP_CORE_ISP_GAMMA_R_Y_2                      0x042C
#define mmISP_CORE_ISP_GAMMA_R_Y_3                      0x0430
#define mmISP_CORE_ISP_GAMMA_R_Y_4                      0x0434
#define mmISP_CORE_ISP_GAMMA_R_Y_5                      0x0438
#define mmISP_CORE_ISP_GAMMA_R_Y_6                      0x043C
#define mmISP_CORE_ISP_GAMMA_R_Y_7                      0x0440
#define mmISP_CORE_ISP_GAMMA_R_Y_8                      0x0444
#define mmISP_CORE_ISP_GAMMA_R_Y_9                      0x0448
#define mmISP_CORE_ISP_GAMMA_R_Y_10                     0x044C
#define mmISP_CORE_ISP_GAMMA_R_Y_11                     0x0450
#define mmISP_CORE_ISP_GAMMA_R_Y_12                     0x0454
#define mmISP_CORE_ISP_GAMMA_R_Y_13                     0x0458
#define mmISP_CORE_ISP_GAMMA_R_Y_14                     0x045C
#define mmISP_CORE_ISP_GAMMA_R_Y_15                     0x0460
#define mmISP_CORE_ISP_GAMMA_R_Y_16                     0x0464
#define mmISP_CORE_ISP_GAMMA_G_Y_0                      0x0468
#define mmISP_CORE_ISP_GAMMA_G_Y_1                      0x046C
#define mmISP_CORE_ISP_GAMMA_G_Y_2                      0x0470
#define mmISP_CORE_ISP_GAMMA_G_Y_3                      0x0474
#define mmISP_CORE_ISP_GAMMA_G_Y_4                      0x0478
#define mmISP_CORE_ISP_GAMMA_G_Y_5                      0x047C
#define mmISP_CORE_ISP_GAMMA_G_Y_6                      0x0480
#define mmISP_CORE_ISP_GAMMA_G_Y_7                      0x0484
#define mmISP_CORE_ISP_GAMMA_G_Y_8                      0x0488
#define mmISP_CORE_ISP_GAMMA_G_Y_9                      0x048C
#define mmISP_CORE_ISP_GAMMA_G_Y_10                     0x0490
#define mmISP_CORE_ISP_GAMMA_G_Y_11                     0x0494
#define mmISP_CORE_ISP_GAMMA_G_Y_12                     0x0498
#define mmISP_CORE_ISP_GAMMA_G_Y_13                     0x049C
#define mmISP_CORE_ISP_GAMMA_G_Y_14                     0x04A0
#define mmISP_CORE_ISP_GAMMA_G_Y_15                     0x04A4
#define mmISP_CORE_ISP_GAMMA_G_Y_16                     0x04A8
#define mmISP_CORE_ISP_GAMMA_B_Y_0                      0x04AC
#define mmISP_CORE_ISP_GAMMA_B_Y_1                      0x04B0
#define mmISP_CORE_ISP_GAMMA_B_Y_2                      0x04B4
#define mmISP_CORE_ISP_GAMMA_B_Y_3                      0x04B8
#define mmISP_CORE_ISP_GAMMA_B_Y_4                      0x04BC
#define mmISP_CORE_ISP_GAMMA_B_Y_5                      0x04C0
#define mmISP_CORE_ISP_GAMMA_B_Y_6                      0x04C4
#define mmISP_CORE_ISP_GAMMA_B_Y_7                      0x04C8
#define mmISP_CORE_ISP_GAMMA_B_Y_8                      0x04CC
#define mmISP_CORE_ISP_GAMMA_B_Y_9                      0x04D0
#define mmISP_CORE_ISP_GAMMA_B_Y_10                     0x04D4
#define mmISP_CORE_ISP_GAMMA_B_Y_11                     0x04D8
#define mmISP_CORE_ISP_GAMMA_B_Y_12                     0x04DC
#define mmISP_CORE_ISP_GAMMA_B_Y_13                     0x04E0
#define mmISP_CORE_ISP_GAMMA_B_Y_14                     0x04E4
#define mmISP_CORE_ISP_GAMMA_B_Y_15                     0x04E8
#define mmISP_CORE_ISP_GAMMA_B_Y_16                     0x04EC
#define mmISP_CORE_ISP_AWB_PROP                         0x0510
#define mmISP_CORE_ISP_AWB_H_OFFS                       0x0514
#define mmISP_CORE_ISP_AWB_V_OFFS                       0x0518
#define mmISP_CORE_ISP_AWB_H_SIZE                       0x051C
#define mmISP_CORE_ISP_AWB_V_SIZE                       0x0520
#define mmISP_CORE_ISP_AWB_FRAMES                       0x0524
#define mmISP_CORE_ISP_AWB_REF                          0x0528
#define mmISP_CORE_ISP_AWB_THRESH                       0x052C
#define mmISP_CORE_ISP_AWB_GAIN_G                       0x0538
#define mmISP_CORE_ISP_AWB_GAIN_RB                      0x053C
#define mmISP_CORE_ISP_AWB_WHITE_CNT                    0x0540
#define mmISP_CORE_ISP_AWB_MEAN                         0x0544
#define mmISP_CORE_ISP_CC_COEFF_0                       0x0570
#define mmISP_CORE_ISP_CC_COEFF_1                       0x0574
#define mmISP_CORE_ISP_CC_COEFF_2                       0x0578
#define mmISP_CORE_ISP_CC_COEFF_3                       0x057C
#define mmISP_CORE_ISP_CC_COEFF_4                       0x0580
#define mmISP_CORE_ISP_CC_COEFF_5                       0x0584
#define mmISP_CORE_ISP_CC_COEFF_6                       0x0588
#define mmISP_CORE_ISP_CC_COEFF_7                       0x058C
#define mmISP_CORE_ISP_CC_COEFF_8                       0x0590
#define mmISP_CORE_ISP_OUT_H_OFFS                       0x0594
#define mmISP_CORE_ISP_OUT_V_OFFS                       0x0598
#define mmISP_CORE_ISP_OUT_H_SIZE                       0x059C
#define mmISP_CORE_ISP_OUT_V_SIZE                       0x05A0
#define mmISP_CORE_ISP_DEMOSAIC                         0x05A4
#define mmISP_CORE_ISP_FLAGS_SHD                        0x05A8
#define mmISP_CORE_ISP_OUT_H_OFFS_SHD                   0x05AC
#define mmISP_CORE_ISP_OUT_V_OFFS_SHD                   0x05B0
#define mmISP_CORE_ISP_OUT_H_SIZE_SHD                   0x05B4
#define mmISP_CORE_ISP_OUT_V_SIZE_SHD                   0x05B8
#define mmISP_CORE_ISP_IMSC                             0x05BC
#define mmISP_CORE_ISP_RIS                              0x05C0
#define mmISP_CORE_ISP_MIS                              0x05C4
#define mmISP_CORE_ISP_ICR                              0x05C8
#define mmISP_CORE_ISP_ISR                              0x05CC
#define mmISP_CORE_ISP_CT_COEFF_0                       0x05D0
#define mmISP_CORE_ISP_CT_COEFF_1                       0x05D4
#define mmISP_CORE_ISP_CT_COEFF_2                       0x05D8
#define mmISP_CORE_ISP_CT_COEFF_3                       0x05DC
#define mmISP_CORE_ISP_CT_COEFF_4                       0x05E0
#define mmISP_CORE_ISP_CT_COEFF_5                       0x05E4
#define mmISP_CORE_ISP_CT_COEFF_6                       0x05E8
#define mmISP_CORE_ISP_CT_COEFF_7                       0x05EC
#define mmISP_CORE_ISP_CT_COEFF_8                       0x05F0
#define mmISP_CORE_ISP_GAMMA_OUT_MODE                   0x05F4
#define mmISP_CORE_ISP_GAMMA_OUT_Y_0                    0x05F8
#define mmISP_CORE_ISP_GAMMA_OUT_Y_1                    0x05FC
#define mmISP_CORE_ISP_GAMMA_OUT_Y_2                    0x0600
#define mmISP_CORE_ISP_GAMMA_OUT_Y_3                    0x0604
#define mmISP_CORE_ISP_GAMMA_OUT_Y_4                    0x0608
#define mmISP_CORE_ISP_GAMMA_OUT_Y_5                    0x060C
#define mmISP_CORE_ISP_GAMMA_OUT_Y_6                    0x0610
#define mmISP_CORE_ISP_GAMMA_OUT_Y_7                    0x0614
#define mmISP_CORE_ISP_GAMMA_OUT_Y_8                    0x0618
#define mmISP_CORE_ISP_GAMMA_OUT_Y_9                    0x061C
#define mmISP_CORE_ISP_GAMMA_OUT_Y_10                   0x0620
#define mmISP_CORE_ISP_GAMMA_OUT_Y_11                   0x0624
#define mmISP_CORE_ISP_GAMMA_OUT_Y_12                   0x0628
#define mmISP_CORE_ISP_GAMMA_OUT_Y_13                   0x062C
#define mmISP_CORE_ISP_GAMMA_OUT_Y_14                   0x0630
#define mmISP_CORE_ISP_GAMMA_OUT_Y_15                   0x0634
#define mmISP_CORE_ISP_GAMMA_OUT_Y_16                   0x0638
#define mmISP_CORE_ISP_ERR                              0x063C
#define mmISP_CORE_ISP_ERR_CLR                          0x0640
#define mmISP_CORE_ISP_FRAME_COUNT                      0x0644
#define mmISP_CORE_ISP_CT_OFFSET_R                      0x0648
#define mmISP_CORE_ISP_CT_OFFSET_G                      0x064C
#define mmISP_CORE_ISP_CT_OFFSET_B                      0x0650
#define mmISP_CORE_ISP_CNR_LINESIZE                     0x0654
#define mmISP_CORE_ISP_CNR_THRESHOLD_C1                 0x0658
#define mmISP_CORE_ISP_CNR_THRESHOLD_C2                 0x065C
#define mmISP_CORE_ISP_FLASH_CMD                        0x0660
#define mmISP_CORE_ISP_FLASH_CONFIG                     0x0664
#define mmISP_CORE_ISP_FLASH_PREDIV                     0x0668
#define mmISP_CORE_ISP_FLASH_DELAY                      0x066C
#define mmISP_CORE_ISP_FLASH_TIME                       0x0670
#define mmISP_CORE_ISP_FLASH_MAXP                       0x0674
#define mmISP_CORE_ISP_SH_CTRL                          0x0680
#define mmISP_CORE_ISP_SH_PREDIV                        0x0684
#define mmISP_CORE_ISP_SH_DELAY                         0x0688
#define mmISP_CORE_ISP_SH_TIME                          0x068C
#define mmISP_CORE_ISP_AFM_CTRL                         0x2000
#define mmISP_CORE_ISP_AFM_LT_A                         0x2004
#define mmISP_CORE_ISP_AFM_RB_A                         0x2008
#define mmISP_CORE_ISP_AFM_LT_B                         0x200C
#define mmISP_CORE_ISP_AFM_RB_B                         0x2010
#define mmISP_CORE_ISP_AFM_LT_C                         0x2014
#define mmISP_CORE_ISP_AFM_RB_C                         0x2018
#define mmISP_CORE_ISP_AFM_THRES                        0x201C
#define mmISP_CORE_ISP_AFM_VAR_SHIFT                    0x2020
#define mmISP_CORE_ISP_AFM_SUM_A                        0x2024
#define mmISP_CORE_ISP_AFM_SUM_B                        0x2028
#define mmISP_CORE_ISP_AFM_SUM_C                        0x202C
#define mmISP_CORE_ISP_AFM_LUM_A                        0x2030
#define mmISP_CORE_ISP_AFM_LUM_B                        0x2034
#define mmISP_CORE_ISP_AFM_LUM_C                        0x2038
#define mmISP_CORE_ISP_VSM_MODE                         0x2100
#define mmISP_CORE_ISP_VSM_H_OFFS                       0x2104
#define mmISP_CORE_ISP_VSM_V_OFFS                       0x2108
#define mmISP_CORE_ISP_VSM_H_SIZE                       0x210C
#define mmISP_CORE_ISP_VSM_V_SIZE                       0x2110
#define mmISP_CORE_ISP_VSM_H_SEGMENTS                   0x2114
#define mmISP_CORE_ISP_VSM_V_SEGMENTS                   0x2118
#define mmISP_CORE_ISP_VSM_DELTA_H                      0x211C
#define mmISP_CORE_ISP_VSM_DELTA_V                      0x2120
#define mmISP_CORE_ISP_LSC_CTRL                         0x2200
#define mmISP_CORE_ISP_LSC_R_TABLE_ADDR                 0x2204
#define mmISP_CORE_ISP_LSC_GR_TABLE_ADDR                0x2208
#define mmISP_CORE_ISP_LSC_B_TABLE_ADDR                 0x220C
#define mmISP_CORE_ISP_LSC_GB_TABLE_ADDR                0x2210
#define mmISP_CORE_ISP_LSC_R_TABLE_DATA                 0x2214
#define mmISP_CORE_ISP_LSC_GR_TABLE_DATA                0x2218
#define mmISP_CORE_ISP_LSC_B_TABLE_DATA                 0x221C
#define mmISP_CORE_ISP_LSC_GB_TABLE_DATA                0x2220
#define mmISP_CORE_ISP_LSC_XGRAD_01                     0x2224
#define mmISP_CORE_ISP_LSC_XGRAD_23                     0x2228
#define mmISP_CORE_ISP_LSC_XGRAD_45                     0x222C
#define mmISP_CORE_ISP_LSC_XGRAD_67                     0x2230
#define mmISP_CORE_ISP_LSC_YGRAD_01                     0x2234
#define mmISP_CORE_ISP_LSC_YGRAD_23                     0x2238
#define mmISP_CORE_ISP_LSC_YGRAD_45                     0x223C
#define mmISP_CORE_ISP_LSC_YGRAD_67                     0x2240
#define mmISP_CORE_ISP_LSC_XSIZE_01                     0x2244
#define mmISP_CORE_ISP_LSC_XSIZE_23                     0x2248
#define mmISP_CORE_ISP_LSC_XSIZE_45                     0x224C
#define mmISP_CORE_ISP_LSC_XSIZE_67                     0x2250
#define mmISP_CORE_ISP_LSC_YSIZE_01                     0x2254
#define mmISP_CORE_ISP_LSC_YSIZE_23                     0x2258
#define mmISP_CORE_ISP_LSC_YSIZE_45                     0x225C
#define mmISP_CORE_ISP_LSC_YSIZE_67                     0x2260
#define mmISP_CORE_ISP_LSC_TABLE_SEL                    0x2264
#define mmISP_CORE_ISP_LSC_STATUS                       0x2268
#define mmISP_CORE_ISP_IS_CTRL                          0x2300
#define mmISP_CORE_ISP_IS_RECENTER                      0x2304
#define mmISP_CORE_ISP_IS_H_OFFS                        0x2308
#define mmISP_CORE_ISP_IS_V_OFFS                        0x230C
#define mmISP_CORE_ISP_IS_H_SIZE                        0x2310
#define mmISP_CORE_ISP_IS_V_SIZE                        0x2314
#define mmISP_CORE_ISP_IS_MAX_DX                        0x2318
#define mmISP_CORE_ISP_IS_MAX_DY                        0x231C
#define mmISP_CORE_ISP_IS_DISPLACE                      0x2320
#define mmISP_CORE_ISP_IS_H_OFFS_SHD                    0x2324
#define mmISP_CORE_ISP_IS_V_OFFS_SHD                    0x2328
#define mmISP_CORE_ISP_IS_H_SIZE_SHD                    0x232C
#define mmISP_CORE_ISP_IS_V_SIZE_SHD                    0x2330
#define mmISP_CORE_ISP_HIST_PROP                        0x2400
#define mmISP_CORE_ISP_HIST_H_OFFS                      0x2404
#define mmISP_CORE_ISP_HIST_V_OFFS                      0x2408
#define mmISP_CORE_ISP_HIST_H_SIZE                      0x240C
#define mmISP_CORE_ISP_HIST_V_SIZE                      0x2410
#define mmISP_CORE_ISP_HIST_BIN_0                       0x2414
#define mmISP_CORE_ISP_HIST_BIN_1                       0x2418
#define mmISP_CORE_ISP_HIST_BIN_2                       0x241C
#define mmISP_CORE_ISP_HIST_BIN_3                       0x2420
#define mmISP_CORE_ISP_HIST_BIN_4                       0x2424
#define mmISP_CORE_ISP_HIST_BIN_5                       0x2428
#define mmISP_CORE_ISP_HIST_BIN_6                       0x242C
#define mmISP_CORE_ISP_HIST_BIN_7                       0x2430
#define mmISP_CORE_ISP_HIST_BIN_8                       0x2434
#define mmISP_CORE_ISP_HIST_BIN_9                       0x2438
#define mmISP_CORE_ISP_HIST_BIN_10                      0x243C
#define mmISP_CORE_ISP_HIST_BIN_11                      0x2440
#define mmISP_CORE_ISP_HIST_BIN_12                      0x2444
#define mmISP_CORE_ISP_HIST_BIN_13                      0x2448
#define mmISP_CORE_ISP_HIST_BIN_14                      0x244C
#define mmISP_CORE_ISP_HIST_BIN_15                      0x2450
#define mmISP_CORE_ISP_HIST_WEIGHT_00TO30               0x2454
#define mmISP_CORE_ISP_HIST_WEIGHT_40TO21               0x2458
#define mmISP_CORE_ISP_HIST_WEIGHT_31TO12               0x245C
#define mmISP_CORE_ISP_HIST_WEIGHT_22TO03               0x2460
#define mmISP_CORE_ISP_HIST_WEIGHT_13TO43               0x2464
#define mmISP_CORE_ISP_HIST_WEIGHT_04TO34               0x2468
#define mmISP_CORE_ISP_HIST_WEIGHT_44                   0x246C
#define mmISP_CORE_ISP_FILT_MODE                        0x2500
#define mmISP_CORE_ISP_FILT_THRESH_BL0                  0x2528
#define mmISP_CORE_ISP_FILT_THRESH_BL1                  0x252C
#define mmISP_CORE_ISP_FILT_THRESH_SH0                  0x2530
#define mmISP_CORE_ISP_FILT_THRESH_SH1                  0x2534
#define mmISP_CORE_ISP_FILT_LUM_WEIGHT                  0x2538
#define mmISP_CORE_ISP_FILT_FAC_SH1                     0x253C
#define mmISP_CORE_ISP_FILT_FAC_SH0                     0x2540
#define mmISP_CORE_ISP_FILT_FAC_MID                     0x2544
#define mmISP_CORE_ISP_FILT_FAC_BL0                     0x2548
#define mmISP_CORE_ISP_FILT_FAC_BL1                     0x254C
#define mmISP_CORE_ISP_CAC_CTRL                         0x2580
#define mmISP_CORE_ISP_CAC_COUNT_START                  0x2584
#define mmISP_CORE_ISP_CAC_A                            0x2588
#define mmISP_CORE_ISP_CAC_B                            0x258C
#define mmISP_CORE_ISP_CAC_C                            0x2590
#define mmISP_CORE_ISP_CAC_X_NORM                       0x2594
#define mmISP_CORE_ISP_CAC_Y_NORM                       0x2598
#define mmISP_CORE_ISP_EXP_CTRL                         0x2600
#define mmISP_CORE_ISP_EXP_H_OFFSET                     0x2604
#define mmISP_CORE_ISP_EXP_V_OFFSET                     0x2608
#define mmISP_CORE_ISP_EXP_H_SIZE                       0x260C
#define mmISP_CORE_ISP_EXP_V_SIZE                       0x2610
#define mmISP_CORE_ISP_EXP_MEAN_00                      0x2614
#define mmISP_CORE_ISP_EXP_MEAN_10                      0x2618
#define mmISP_CORE_ISP_EXP_MEAN_20                      0x261C
#define mmISP_CORE_ISP_EXP_MEAN_30                      0x2620
#define mmISP_CORE_ISP_EXP_MEAN_40                      0x2624
#define mmISP_CORE_ISP_EXP_MEAN_01                      0x2628
#define mmISP_CORE_ISP_EXP_MEAN_11                      0x262C
#define mmISP_CORE_ISP_EXP_MEAN_21                      0x2630
#define mmISP_CORE_ISP_EXP_MEAN_31                      0x2634
#define mmISP_CORE_ISP_EXP_MEAN_41                      0x2638
#define mmISP_CORE_ISP_EXP_MEAN_02                      0x263C
#define mmISP_CORE_ISP_EXP_MEAN_12                      0x2640
#define mmISP_CORE_ISP_EXP_MEAN_22                      0x2644
#define mmISP_CORE_ISP_EXP_MEAN_32                      0x2648
#define mmISP_CORE_ISP_EXP_MEAN_42                      0x264C
#define mmISP_CORE_ISP_EXP_MEAN_03                      0x2650
#define mmISP_CORE_ISP_EXP_MEAN_13                      0x2654
#define mmISP_CORE_ISP_EXP_MEAN_23                      0x2658
#define mmISP_CORE_ISP_EXP_MEAN_33                      0x265C
#define mmISP_CORE_ISP_EXP_MEAN_43                      0x2660
#define mmISP_CORE_ISP_EXP_MEAN_04                      0x2664
#define mmISP_CORE_ISP_EXP_MEAN_14                      0x2668
#define mmISP_CORE_ISP_EXP_MEAN_24                      0x266C
#define mmISP_CORE_ISP_EXP_MEAN_34                      0x2670
#define mmISP_CORE_ISP_EXP_MEAN_44                      0x2674
#define mmISP_CORE_ISP_BLS_CTRL                         0x2700
#define mmISP_CORE_ISP_BLS_SAMPLES                      0x2704
#define mmISP_CORE_ISP_BLS_H1_START                     0x2708
#define mmISP_CORE_ISP_BLS_H1_STOP                      0x270C
#define mmISP_CORE_ISP_BLS_V1_START                     0x2710
#define mmISP_CORE_ISP_BLS_V1_STOP                      0x2714
#define mmISP_CORE_ISP_BLS_H2_START                     0x2718
#define mmISP_CORE_ISP_BLS_H2_STOP                      0x271C
#define mmISP_CORE_ISP_BLS_V2_START                     0x2720
#define mmISP_CORE_ISP_BLS_V2_STOP                      0x2724
#define mmISP_CORE_ISP_BLS_A_FIXED                      0x2728
#define mmISP_CORE_ISP_BLS_B_FIXED                      0x272C
#define mmISP_CORE_ISP_BLS_C_FIXED                      0x2730
#define mmISP_CORE_ISP_BLS_D_FIXED                      0x2734
#define mmISP_CORE_ISP_BLS_A_MEASURED                   0x2738
#define mmISP_CORE_ISP_BLS_B_MEASURED                   0x273C
#define mmISP_CORE_ISP_BLS_C_MEASURED                   0x2740
#define mmISP_CORE_ISP_BLS_D_MEASURED                   0x2744
#define mmISP_CORE_ISP_BNR_MODE                         0x2800
#define mmISP_CORE_ISP_BNR_STRENGTH_R                   0x2804
#define mmISP_CORE_ISP_BNR_STRENGTH_G                   0x2808
#define mmISP_CORE_ISP_BNR_STRENGTH_B                   0x280C
#define mmISP_CORE_ISP_BNR_S_WEIGHT_G_1_4               0x2810
#define mmISP_CORE_ISP_BNR_S_WEIGHT_G_5_6               0x2814
#define mmISP_CORE_ISP_BNR_S_WEIGHT_RB_1_4              0x2818
#define mmISP_CORE_ISP_BNR_S_WEIGHT_RB_5_6              0x281C
#define mmISP_CORE_ISP_BNR_NLL_COEFF_0                  0x2820
#define mmISP_CORE_ISP_BNR_NLL_COEFF_1                  0x2824
#define mmISP_CORE_ISP_BNR_NLL_COEFF_2                  0x2828
#define mmISP_CORE_ISP_BNR_NLL_COEFF_3                  0x282C
#define mmISP_CORE_ISP_BNR_NLL_COEFF_4                  0x2830
#define mmISP_CORE_ISP_BNR_NLL_COEFF_5                  0x2834
#define mmISP_CORE_ISP_BNR_NLL_COEFF_6                  0x2838
#define mmISP_CORE_ISP_BNR_NLL_COEFF_7                  0x283C
#define mmISP_CORE_ISP_BNR_NLL_COEFF_8                  0x2840
#define mmISP_CORE_ISP_BNR_NLL_COEFF_9                  0x2844
#define mmISP_CORE_ISP_BNR_NLL_COEFF_10                 0x2848
#define mmISP_CORE_ISP_BNR_NLL_COEFF_11                 0x284C
#define mmISP_CORE_ISP_BNR_NLL_COEFF_12                 0x2850
#define mmISP_CORE_ISP_BNR_NLL_COEFF_13                 0x2854
#define mmISP_CORE_ISP_BNR_NLL_COEFF_14                 0x2858
#define mmISP_CORE_ISP_BNR_NLL_COEFF_15                 0x285C
#define mmISP_CORE_ISP_BNR_NLL_COEFF_16                 0x2860
#define mmISP_CORE_ISP_BNR_NF_GAIN_R                    0x2864
#define mmISP_CORE_ISP_BNR_NF_GAIN_GR                   0x2868
#define mmISP_CORE_ISP_BNR_NF_GAIN_GB                   0x286C
#define mmISP_CORE_ISP_BNR_NF_GAIN_B                    0x2870
#define mmISP_CORE_ISP_DPC_MODE                         0x2900
#define mmISP_CORE_ISP_DPC_OUTPUT_MODE                  0x2904
#define mmISP_CORE_ISP_DPC_SET_USE                      0x2908
#define mmISP_CORE_ISP_DPC_METHODS_SET_1                0x290C
#define mmISP_CORE_ISP_DPC_METHODS_SET_2                0x2910
#define mmISP_CORE_ISP_DPC_METHODS_SET_3                0x2914
#define mmISP_CORE_ISP_DPC_LINE_THRESH_1                0x2918
#define mmISP_CORE_ISP_DPC_LINE_MAD_FAC_1               0x291C
#define mmISP_CORE_ISP_DPC_PG_FAC_1                     0x2920
#define mmISP_CORE_ISP_DPC_RND_THRESH_1                 0x2924
#define mmISP_CORE_ISP_DPC_RG_FAC_1                     0x2928
#define mmISP_CORE_ISP_DPC_LINE_THRESH_2                0x292C
#define mmISP_CORE_ISP_DPC_LINE_MAD_FAC_2               0x2930
#define mmISP_CORE_ISP_DPC_PG_FAC_2                     0x2934
#define mmISP_CORE_ISP_DPC_RND_THRESH_2                 0x2938
#define mmISP_CORE_ISP_DPC_RG_FAC_2                     0x293C
#define mmISP_CORE_ISP_DPC_LINE_THRESH_3                0x2940
#define mmISP_CORE_ISP_DPC_LINE_MAD_FAC_3               0x2944
#define mmISP_CORE_ISP_DPC_PG_FAC_3                     0x2948
#define mmISP_CORE_ISP_DPC_RND_THRESH_3                 0x294C
#define mmISP_CORE_ISP_DPC_RG_FAC_3                     0x2950
#define mmISP_CORE_ISP_DPC_RO_LIMITS                    0x2954
#define mmISP_CORE_ISP_DPC_RND_OFFS                     0x2958
#define mmISP_CORE_ISP_DPC_BPT_CTRL                     0x295C
#define mmISP_CORE_ISP_DPC_BPT_NUMBER                   0x2960
#define mmISP_CORE_ISP_DPC_BPT_ADDR                     0x2964
#define mmISP_CORE_ISP_DPC_BPT_DATA                     0x2968
#define mmISP_CORE_ISP_WDR_CTRL                         0x2A00
#define mmISP_CORE_ISP_WDR_TONECURVE_1                  0x2A04
#define mmISP_CORE_ISP_WDR_TONECURVE_2                  0x2A08
#define mmISP_CORE_ISP_WDR_TONECURVE_3                  0x2A0C
#define mmISP_CORE_ISP_WDR_TONECURVE_4                  0x2A10
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_0               0x2A14
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_1               0x2A18
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_2               0x2A1C
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_3               0x2A20
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_4               0x2A24
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_5               0x2A28
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_6               0x2A2C
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_7               0x2A30
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_8               0x2A34
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_9               0x2A38
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_10              0x2A3C
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_11              0x2A40
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_12              0x2A44
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_13              0x2A48
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_14              0x2A4C
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_15              0x2A50
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_16              0x2A54
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_17              0x2A58
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_18              0x2A5C
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_19              0x2A60
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_20              0x2A64
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_21              0x2A68
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_22              0x2A6C
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_23              0x2A70
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_24              0x2A74
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_25              0x2A78
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_26              0x2A7C
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_27              0x2A80
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_28              0x2A84
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_29              0x2A88
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_30              0x2A8C
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_31              0x2A90
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_32              0x2A94
#define mmISP_CORE_ISP_WDR_OFFSET                       0x2A98
#define mmISP_CORE_ISP_WDR_DELTAMIN                     0x2A9C
#define mmISP_CORE_ISP_WDR_TONECURVE_1_SHD              0x2AA0
#define mmISP_CORE_ISP_WDR_TONECURVE_2_SHD              0x2AA4
#define mmISP_CORE_ISP_WDR_TONECURVE_3_SHD              0x2AA8
#define mmISP_CORE_ISP_WDR_TONECURVE_4_SHD              0x2AAC
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_0           0x2AB0
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_1           0x2AB4
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_2           0x2AB8
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_3           0x2ABC
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_4           0x2AC0
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_5           0x2AC4
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_6           0x2AC8
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_7           0x2ACC
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_8           0x2AD0
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_9           0x2AD4
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_10          0x2AD8
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_11          0x2ADC
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_12          0x2AE0
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_13          0x2AE4
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_14          0x2AE8
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_15          0x2AEC
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_16          0x2AF0
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_17          0x2AF4
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_18          0x2AF8
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_19          0x2AFC
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_20          0x2B00
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_21          0x2B04
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_22          0x2B08
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_23          0x2B0C
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_24          0x2B10
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_25          0x2B14
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_26          0x2B18
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_27          0x2B1C
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_28          0x2B20
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_29          0x2B24
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_30          0x2B28
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_31          0x2B2C
#define mmISP_CORE_ISP_WDR_TONECURVE_YM_SHD_32          0x2B30
#define mmISP_CORE_CPROC_CTRL                           0x0800
#define mmISP_CORE_CPROC_CONTRAST                       0x0804
#define mmISP_CORE_CPROC_BRIGHTNESS                     0x0808
#define mmISP_CORE_CPROC_SATURATION                     0x080C
#define mmISP_CORE_CPROC_HUE                            0x0810
#define mmISP_CORE_H_FLIP_Y_PIC_WIDTH_INIT              0x0900
#define mmISP_CORE_H_FLIP_CTRL                          0x0904
#define mmISP_CORE_H_FLIP_Y_PIC_WIDTH_SHD               0x0908
#define mmISP_CORE_H_FLIP_CTRL_SHD                      0x090C
#define mmISP_CORE_MRSZ_CTRL                            0x0100
#define mmISP_CORE_MRSZ_SCALE_HY                        0x0104
#define mmISP_CORE_MRSZ_SCALE_HCB                       0x0108
#define mmISP_CORE_MRSZ_SCALE_HCR                       0x010C
#define mmISP_CORE_MRSZ_SCALE_VY                        0x0110
#define mmISP_CORE_MRSZ_SCALE_VC                        0x0114
#define mmISP_CORE_MRSZ_PHASE_HY                        0x0118
#define mmISP_CORE_MRSZ_PHASE_HC                        0x011C
#define mmISP_CORE_MRSZ_PHASE_VY                        0x0120
#define mmISP_CORE_MRSZ_PHASE_VC                        0x0124
#define mmISP_CORE_MRSZ_SCALE_LUT_ADDR                  0x0128
#define mmISP_CORE_MRSZ_SCALE_LUT                       0x012C
#define mmISP_CORE_MRSZ_CTRL_SHD                        0x0130
#define mmISP_CORE_MRSZ_SCALE_HY_SHD                    0x0134
#define mmISP_CORE_MRSZ_SCALE_HCB_SHD                   0x0138
#define mmISP_CORE_MRSZ_SCALE_HCR_SHD                   0x013C
#define mmISP_CORE_MRSZ_SCALE_VY_SHD                    0x0140
#define mmISP_CORE_MRSZ_SCALE_VC_SHD                    0x0144
#define mmISP_CORE_MRSZ_PHASE_HY_SHD                    0x0148
#define mmISP_CORE_MRSZ_PHASE_HC_SHD                    0x014C
#define mmISP_CORE_MRSZ_PHASE_VY_SHD                    0x0150
#define mmISP_CORE_MRSZ_PHASE_VC_SHD                    0x0154
#define mmISP_CORE_MRSZ_HEIGHT_SRC                      0x0158
#define mmISP_CORE_MRSZ_COEFF_SUM_HY                    0x015C
#define mmISP_CORE_MRSZ_COEFF_SUM_VY                    0x0160
#define mmISP_CORE_MRSZ_COEFF_SUM_HC                    0x0164
#define mmISP_CORE_MRSZ_COEFF_SUM_VC                    0x0168
#define mmISP_CORE_MRSZ_HEIGHT_SRC_SHD                  0x016C
#define mmISP_CORE_MRSZ_COEFF_SUM_HY_SHD                0x0170
#define mmISP_CORE_MRSZ_COEFF_SUM_VY_SHD                0x0174
#define mmISP_CORE_MRSZ_COEFF_SUM_HC_SHD                0x0178
#define mmISP_CORE_MRSZ_COEFF_SUM_VC_SHD                0x017C
#define mmISP_CORE_VRSZ_CTRL                            0x0200
#define mmISP_CORE_VRSZ_SCALE_HY                        0x0204
#define mmISP_CORE_VRSZ_SCALE_HCB                       0x0208
#define mmISP_CORE_VRSZ_SCALE_HCR                       0x020C
#define mmISP_CORE_VRSZ_SCALE_VY                        0x0210
#define mmISP_CORE_VRSZ_SCALE_VC                        0x0214
#define mmISP_CORE_VRSZ_PHASE_HY                        0x0218
#define mmISP_CORE_VRSZ_PHASE_HC                        0x021C
#define mmISP_CORE_VRSZ_PHASE_VY                        0x0220
#define mmISP_CORE_VRSZ_PHASE_VC                        0x0224
#define mmISP_CORE_VRSZ_SCALE_LUT_ADDR                  0x0228
#define mmISP_CORE_VRSZ_SCALE_LUT                       0x022C
#define mmISP_CORE_VRSZ_CTRL_SHD                        0x0230
#define mmISP_CORE_VRSZ_SCALE_HY_SHD                    0x0234
#define mmISP_CORE_VRSZ_SCALE_HCB_SHD                   0x0238
#define mmISP_CORE_VRSZ_SCALE_HCR_SHD                   0x023C
#define mmISP_CORE_VRSZ_SCALE_VY_SHD                    0x0240
#define mmISP_CORE_VRSZ_SCALE_VC_SHD                    0x0244
#define mmISP_CORE_VRSZ_PHASE_HY_SHD                    0x0248
#define mmISP_CORE_VRSZ_PHASE_HC_SHD                    0x024C
#define mmISP_CORE_VRSZ_PHASE_VY_SHD                    0x0250
#define mmISP_CORE_VRSZ_PHASE_VC_SHD                    0x0254
#define mmISP_CORE_VRSZ_HEIGHT_SRC                      0x0258
#define mmISP_CORE_VRSZ_COEFF_SUM_HY                    0x025C
#define mmISP_CORE_VRSZ_COEFF_SUM_VY                    0x0260
#define mmISP_CORE_VRSZ_COEFF_SUM_HC                    0x0264
#define mmISP_CORE_VRSZ_COEFF_SUM_VC                    0x0268
#define mmISP_CORE_VRSZ_HEIGHT_SRC_SHD                  0x026C
#define mmISP_CORE_VRSZ_COEFF_SUM_HY_SHD                0x0270
#define mmISP_CORE_VRSZ_COEFF_SUM_VY_SHD                0x0274
#define mmISP_CORE_VRSZ_COEFF_SUM_HC_SHD                0x0278
#define mmISP_CORE_VRSZ_COEFF_SUM_VC_SHD                0x027C
#define mmISP_CORE_PRSZ_CTRL                            0x0300
#define mmISP_CORE_PRSZ_SCALE_HY                        0x0304
#define mmISP_CORE_PRSZ_SCALE_HCB                       0x0308
#define mmISP_CORE_PRSZ_SCALE_HCR                       0x030C
#define mmISP_CORE_PRSZ_SCALE_VY                        0x0310
#define mmISP_CORE_PRSZ_SCALE_VC                        0x0314
#define mmISP_CORE_PRSZ_PHASE_HY                        0x0318
#define mmISP_CORE_PRSZ_PHASE_HC                        0x031C
#define mmISP_CORE_PRSZ_PHASE_VY                        0x0320
#define mmISP_CORE_PRSZ_PHASE_VC                        0x0324
#define mmISP_CORE_PRSZ_SCALE_LUT_ADDR                  0x0328
#define mmISP_CORE_PRSZ_SCALE_LUT                       0x032C
#define mmISP_CORE_PRSZ_CTRL_SHD                        0x0330
#define mmISP_CORE_PRSZ_SCALE_HY_SHD                    0x0334
#define mmISP_CORE_PRSZ_SCALE_HCB_SHD                   0x0338
#define mmISP_CORE_PRSZ_SCALE_HCR_SHD                   0x033C
#define mmISP_CORE_PRSZ_SCALE_VY_SHD                    0x0340
#define mmISP_CORE_PRSZ_SCALE_VC_SHD                    0x0344
#define mmISP_CORE_PRSZ_PHASE_HY_SHD                    0x0348
#define mmISP_CORE_PRSZ_PHASE_HC_SHD                    0x034C
#define mmISP_CORE_PRSZ_PHASE_VY_SHD                    0x0350
#define mmISP_CORE_PRSZ_PHASE_VC_SHD                    0x0354
#define mmISP_CORE_PRSZ_HEIGHT_SRC                      0x0358
#define mmISP_CORE_PRSZ_COEFF_SUM_HY                    0x035C
#define mmISP_CORE_PRSZ_COEFF_SUM_VY                    0x0360
#define mmISP_CORE_PRSZ_COEFF_SUM_HC                    0x0364
#define mmISP_CORE_PRSZ_COEFF_SUM_VC                    0x0368
#define mmISP_CORE_PRSZ_HEIGHT_SRC_SHD                  0x036C
#define mmISP_CORE_PRSZ_COEFF_SUM_HY_SHD                0x0370
#define mmISP_CORE_PRSZ_COEFF_SUM_VY_SHD                0x0374
#define mmISP_CORE_PRSZ_COEFF_SUM_HC_SHD                0x0378
#define mmISP_CORE_PRSZ_COEFF_SUM_VC_SHD                0x037C
#define mmISP_CORE_PREP_CTRL                            0x1000
#define mmISP_CORE_PREP_IMSC                            0x1004
#define mmISP_CORE_PREP_RIS                             0x1008
#define mmISP_CORE_PREP_MIS                             0x100C
#define mmISP_CORE_PREP_ICR                             0x1010
#define mmISP_CORE_PREP_ISR                             0x1014
#define mmISP_CORE_PREP_FLAGS_SHD                       0x1018
#define mmISP_CORE_PREP_ACQ_PROP                        0x101C
#define mmISP_CORE_PREP_ACQ_H_OFFS                      0x1020
#define mmISP_CORE_PREP_ACQ_V_OFFS                      0x1024
#define mmISP_CORE_PREP_ACQ_H_SIZE                      0x1028
#define mmISP_CORE_PREP_ACQ_V_SIZE                      0x102C
#define mmISP_CORE_PREP_OUT_H_OFFS                      0x1030
#define mmISP_CORE_PREP_OUT_V_OFFS                      0x1034
#define mmISP_CORE_PREP_OUT_H_SIZE                      0x1038
#define mmISP_CORE_PREP_OUT_V_SIZE                      0x103C
#define mmISP_CORE_PREP_ERR                             0x1050
#define mmISP_CORE_PREP_ERR_CLR                         0x1054
#define mmISP_CORE_PREP_BLS_CTRL                        0x1200
#define mmISP_CORE_PREP_BLS_SAMPLES                     0x1204
#define mmISP_CORE_PREP_BLS_H1_START                    0x1208
#define mmISP_CORE_PREP_BLS_H1_STOP                     0x120C
#define mmISP_CORE_PREP_BLS_V1_START                    0x1210
#define mmISP_CORE_PREP_BLS_V1_STOP                     0x1214
#define mmISP_CORE_PREP_BLS_A_FIXED                     0x1228
#define mmISP_CORE_PREP_BLS_B_FIXED                     0x122C
#define mmISP_CORE_PREP_BLS_C_FIXED                     0x1230
#define mmISP_CORE_PREP_BLS_D_FIXED                     0x1234
#define mmISP_CORE_PREP_BLS_A_MEASURED                  0x1238
#define mmISP_CORE_PREP_BLS_B_MEASURED                  0x123C
#define mmISP_CORE_PREP_BLS_C_MEASURED                  0x1240
#define mmISP_CORE_PREP_BLS_D_MEASURED                  0x1244
#define mmISP_CORE_PREP_GAMMA_CTRL                      0x1400
#define mmISP_CORE_PREP_GAMMA_DX_LO                     0x1404
#define mmISP_CORE_PREP_GAMMA_DX_HI                     0x1408
#define mmISP_CORE_PREP_GAMMA_R_Y_0                     0x140C
#define mmISP_CORE_PREP_GAMMA_R_Y_1                     0x1410
#define mmISP_CORE_PREP_GAMMA_R_Y_2                     0x1414
#define mmISP_CORE_PREP_GAMMA_R_Y_3                     0x1418
#define mmISP_CORE_PREP_GAMMA_R_Y_4                     0x141C
#define mmISP_CORE_PREP_GAMMA_R_Y_5                     0x1420
#define mmISP_CORE_PREP_GAMMA_R_Y_6                     0x1424
#define mmISP_CORE_PREP_GAMMA_R_Y_7                     0x1428
#define mmISP_CORE_PREP_GAMMA_R_Y_8                     0x142C
#define mmISP_CORE_PREP_GAMMA_R_Y_9                     0x1430
#define mmISP_CORE_PREP_GAMMA_R_Y_10                    0x1434
#define mmISP_CORE_PREP_GAMMA_R_Y_11                    0x1438
#define mmISP_CORE_PREP_GAMMA_R_Y_12                    0x143C
#define mmISP_CORE_PREP_GAMMA_R_Y_13                    0x1440
#define mmISP_CORE_PREP_GAMMA_R_Y_14                    0x1444
#define mmISP_CORE_PREP_GAMMA_R_Y_15                    0x1448
#define mmISP_CORE_PREP_GAMMA_R_Y_16                    0x144C
#define mmISP_CORE_PREP_GAMMA_G_Y_0                     0x1450
#define mmISP_CORE_PREP_GAMMA_G_Y_1                     0x1454
#define mmISP_CORE_PREP_GAMMA_G_Y_2                     0x1458
#define mmISP_CORE_PREP_GAMMA_G_Y_3                     0x145C
#define mmISP_CORE_PREP_GAMMA_G_Y_4                     0x1460
#define mmISP_CORE_PREP_GAMMA_G_Y_5                     0x1464
#define mmISP_CORE_PREP_GAMMA_G_Y_6                     0x1468
#define mmISP_CORE_PREP_GAMMA_G_Y_7                     0x146C
#define mmISP_CORE_PREP_GAMMA_G_Y_8                     0x1470
#define mmISP_CORE_PREP_GAMMA_G_Y_9                     0x1474
#define mmISP_CORE_PREP_GAMMA_G_Y_10                    0x1478
#define mmISP_CORE_PREP_GAMMA_G_Y_11                    0x147C
#define mmISP_CORE_PREP_GAMMA_G_Y_12                    0x1480
#define mmISP_CORE_PREP_GAMMA_G_Y_13                    0x1484
#define mmISP_CORE_PREP_GAMMA_G_Y_14                    0x1488
#define mmISP_CORE_PREP_GAMMA_G_Y_15                    0x148C
#define mmISP_CORE_PREP_GAMMA_G_Y_16                    0x1490
#define mmISP_CORE_PREP_GAMMA_B_Y_0                     0x1494
#define mmISP_CORE_PREP_GAMMA_B_Y_1                     0x1498
#define mmISP_CORE_PREP_GAMMA_B_Y_2                     0x149C
#define mmISP_CORE_PREP_GAMMA_B_Y_3                     0x14A0
#define mmISP_CORE_PREP_GAMMA_B_Y_4                     0x14A4
#define mmISP_CORE_PREP_GAMMA_B_Y_5                     0x14A8
#define mmISP_CORE_PREP_GAMMA_B_Y_6                     0x14AC
#define mmISP_CORE_PREP_GAMMA_B_Y_7                     0x14B0
#define mmISP_CORE_PREP_GAMMA_B_Y_8                     0x14B4
#define mmISP_CORE_PREP_GAMMA_B_Y_9                     0x14B8
#define mmISP_CORE_PREP_GAMMA_B_Y_10                    0x14BC
#define mmISP_CORE_PREP_GAMMA_B_Y_11                    0x14C0
#define mmISP_CORE_PREP_GAMMA_B_Y_12                    0x14C4
#define mmISP_CORE_PREP_GAMMA_B_Y_13                    0x14C8
#define mmISP_CORE_PREP_GAMMA_B_Y_14                    0x14CC
#define mmISP_CORE_PREP_GAMMA_B_Y_15                    0x14D0
#define mmISP_CORE_PREP_GAMMA_B_Y_16                    0x14D4
#define mmISP_CORE_PREP_LSC_CTRL                        0x1600
#define mmISP_CORE_PREP_LSC_R_TABLE_ADDR                0x1604
#define mmISP_CORE_PREP_LSC_GR_TABLE_ADDR               0x1608
#define mmISP_CORE_PREP_LSC_B_TABLE_ADDR                0x160C
#define mmISP_CORE_PREP_LSC_GB_TABLE_ADDR               0x1610
#define mmISP_CORE_PREP_LSC_R_TABLE_DATA                0x1614
#define mmISP_CORE_PREP_LSC_GR_TABLE_DATA               0x1618
#define mmISP_CORE_PREP_LSC_B_TABLE_DATA                0x161C
#define mmISP_CORE_PREP_LSC_GB_TABLE_DATA               0x1620
#define mmISP_CORE_PREP_LSC_XGRAD_01                    0x1624
#define mmISP_CORE_PREP_LSC_XGRAD_23                    0x1628
#define mmISP_CORE_PREP_LSC_XGRAD_45                    0x162C
#define mmISP_CORE_PREP_LSC_XGRAD_67                    0x1630
#define mmISP_CORE_PREP_LSC_YGRAD_01                    0x1634
#define mmISP_CORE_PREP_LSC_YGRAD_23                    0x1638
#define mmISP_CORE_PREP_LSC_YGRAD_45                    0x163C
#define mmISP_CORE_PREP_LSC_YGRAD_67                    0x1640
#define mmISP_CORE_PREP_LSC_XSIZE_01                    0x1644
#define mmISP_CORE_PREP_LSC_XSIZE_23                    0x1648
#define mmISP_CORE_PREP_LSC_XSIZE_45                    0x164C
#define mmISP_CORE_PREP_LSC_XSIZE_67                    0x1650
#define mmISP_CORE_PREP_LSC_XSIZE_89                    0x1654
#define mmISP_CORE_PREP_LSC_XSIZE_AB                    0x1658
#define mmISP_CORE_PREP_LSC_XSIZE_CD                    0x165C
#define mmISP_CORE_PREP_LSC_XSIZE_EF                    0x1660
#define mmISP_CORE_PREP_LSC_YSIZE_01                    0x1664
#define mmISP_CORE_PREP_LSC_YSIZE_23                    0x1668
#define mmISP_CORE_PREP_LSC_YSIZE_45                    0x166C
#define mmISP_CORE_PREP_LSC_YSIZE_67                    0x1670
#define mmISP_CORE_PREP_LSC_YSIZE_89                    0x1674
#define mmISP_CORE_PREP_LSC_YSIZE_AB                    0x1678
#define mmISP_CORE_PREP_LSC_YSIZE_CD                    0x167C
#define mmISP_CORE_PREP_LSC_YSIZE_EF                    0x1680
#define mmISP_CORE_PREP_LSC_TL_OFFSET                   0x1684
#define mmISP_CORE_PREP_LSC_BR_OFFSET                   0x1688
#define mmISP_CORE_PREP_LSC_TABLE_SEL                   0x178C
#define mmISP_CORE_PREP_LSC_STATUS                      0x1790


// Registers from MI_WR_MP block

#define mmISP_CORE_MI_MP_CTRL                           0x3000
#define mmISP_CORE_MI_MP_CTRL2                          0x3004
#define mmISP_CORE_MI_MP_INIT                           0x3008
#define mmISP_CORE_MI_MP_INIT2                          0x300C
#define mmISP_CORE_MI_MP_Y_BASE_AD_INIT                 0x3010
#define mmISP_CORE_MI_MP_Y_BASE_AD_H_INIT               0x3014
#define mmISP_CORE_MI_MP_Y_SIZE_INIT                    0x3018
#define mmISP_CORE_MI_MP_Y_IRQ_OFFS_INIT                0x301C
#define mmISP_CORE_MI_MP_Y_LLENGTH_INIT                 0x3020
#define mmISP_CORE_MI_MP_CB_BASE_AD_INIT                0x3024
#define mmISP_CORE_MI_MP_CB_BASE_AD_H_INIT              0x3028
#define mmISP_CORE_MI_MP_CB_SIZE_INIT                   0x302C
#define mmISP_CORE_MI_MP_CB_IRQ_OFFS_INIT               0x3030
#define mmISP_CORE_MI_MP_CB_LLENGTH_INIT                0x3034
#define mmISP_CORE_MI_MP_CR_BASE_AD_INIT                0x3038
#define mmISP_CORE_MI_MP_CR_BASE_AD_H_INIT              0x303C
#define mmISP_CORE_MI_MP_CR_SIZE_INIT                   0x3040
#define mmISP_CORE_MI_MP_CR_IRQ_OFFS_INIT               0x3044
#define mmISP_CORE_MI_MP_CR_LLENGTH_INIT                0x3048
#define mmISP_CORE_MI_MP_CTRL_SHD                       0x304C
#define mmISP_CORE_MI_MP_Y_BASE_AD_SHD                  0x3050
#define mmISP_CORE_MI_MP_Y_BASE_AD_H_SHD                0x3054
#define mmISP_CORE_MI_MP_Y_SIZE_SHD                     0x3058
#define mmISP_CORE_MI_MP_Y_IRQ_OFFS_SHD                 0x305C
#define mmISP_CORE_MI_MP_Y_LLENGTH_SHD                  0x3060
#define mmISP_CORE_MI_MP_CB_BASE_AD_SHD                 0x3064
#define mmISP_CORE_MI_MP_CB_BASE_AD_H_SHD               0x3068
#define mmISP_CORE_MI_MP_CB_SIZE_SHD                    0x306C
#define mmISP_CORE_MI_MP_CB_IRQ_OFFS_SHD                0x3070
#define mmISP_CORE_MI_MP_CB_LLENGTH_SHD                 0x3074
#define mmISP_CORE_MI_MP_CR_BASE_AD_SHD                 0x3078
#define mmISP_CORE_MI_MP_CR_BASE_AD_H_SHD               0x307C
#define mmISP_CORE_MI_MP_CR_SIZE_SHD                    0x3080
#define mmISP_CORE_MI_MP_CR_IRQ_OFFS_SHD                0x3084
#define mmISP_CORE_MI_MP_CR_LLENGTH_SHD                 0x3088
#define mmISP_CORE_MI_MP_IMSC                           0x308C
#define mmISP_CORE_MI_MP_RIS                            0x3090
#define mmISP_CORE_MI_MP_MIS                            0x3094
#define mmISP_CORE_MI_MP_ICR                            0x3098
#define mmISP_CORE_MI_MP_ISR                            0x309C
#define mmISP_CORE_MI_MP_STATUS                         0x30A0
#define mmISP_CORE_MI_MP_STATUS_CLR                     0x30A4
#define mmISP_CORE_MI_MP_RAW_BYTE_CNT                   0x30A8
#define mmISP_CORE_MI_MP_DP_PIXEL_CNT                   0x30AC
#define mmISP_CORE_MI_MP_MCH0_BYTE_CNT                  0x30B0
#define mmISP_CORE_MI_MP_MCH1_BYTE_CNT                  0x30B4
#define mmISP_CORE_MI_MP_MCH2_BYTE_CNT                  0x30B8
#define mmISP_CORE_MI_MP_PSTATE_CTRL_Y                  0x30C0
#define mmISP_CORE_MI_MP_PSTATE_CTRL_CB                 0x30C4
#define mmISP_CORE_MI_MP_PSTATE_CTRL_CR                 0x30C8
#define mmISP_CORE_MI_MP_PSTATE_ALLOW_STAT              0x30CC
#define mmISP_CORE_MI_MP_CID_ENABLE                     0x30D8
#define mmISP_CORE_MI_MP_LEAK_ENABLE                    0x30DC
#define mmISP_CORE_MI_MP_LEAK_TH_Y                      0x30E0
#define mmISP_CORE_MI_MP_LEAK_TH_CB                     0x30E4
#define mmISP_CORE_MI_MP_LEAK_TH_CR                     0x30E8
#define mmISP_CORE_MI_MP_TIMER_EN                       0x30EC
#define mmISP_CORE_MI_MP_TIMER_TH                       0x30F0
#define mmISP_CORE_MI_MP_CUR_LEAK_STATUS                0x30FC
#define mmISP_CORE_MI_MP_SRAM_FILL_LEVEL_Y              0x3100
#define mmISP_CORE_MI_MP_SRAM_FILL_LEVEL_CB             0x3104
#define mmISP_CORE_MI_MP_SRAM_FILL_LEVEL_CR             0x3108
#define mmISP_CORE_MI_MP_FIFO_OVERFLOW                  0x310C
#define mmISP_CORE_MI_MP_MAFD                           0x3120
#define mmISP_CORE_MI_MP_SPH_TEST                       0x3124
#define mmISP_CORE_MI_MP_SPH_WDATA                      0x3128
#define mmISP_CORE_MI_MP_STALL                          0x312C
#define mmISP_CORE_MI_MP_AXI_GENERAL                    0x3140
#define mmISP_CORE_MI_MP_AXI_AWUSER                     0x3144
#define mmISP_CORE_MI_MP_AXI_WUSER                      0x3148
#define mmISP_CORE_MI_MP_QOS_CTRL                       0x314C
#define mmISP_CORE_MI_MP_PFM_CTRL                       0x3150
#define mmISP_CORE_MI_MP_PFM_REGION_SET0                0x3154
#define mmISP_CORE_MI_MP_PFM_REGION_SET1                0x3158
#define mmISP_CORE_MI_MP_PFM_REGION_SET2                0x315C
#define mmISP_CORE_MI_MP_PFM_REGION_SET3                0x3160
#define mmISP_CORE_MI_MP_PFM_REGION_SET4                0x3164
#define mmISP_CORE_MI_MP_PFM_REGION_SET5                0x3168
#define mmISP_CORE_MI_MP_PFM_REGION_SET6                0x316C
#define mmISP_CORE_MI_MP_PFM_REGION_SET7                0x3170
#define mmISP_CORE_MI_MP_PFM_STAT_0_1_CNT               0x3174
#define mmISP_CORE_MI_MP_PFM_STAT_2_3_CNT               0x3178
#define mmISP_CORE_MI_MP_PFM_STAT_4_5_CNT               0x317C
#define mmISP_CORE_MI_MP_PFM_STAT_6_7_CNT               0x3180
#define mmISP_CORE_MI_MP_CTRL_CRC                       0x3190
#define mmISP_CORE_MI_MP_CRC0                           0x3194
#define mmISP_CORE_MI_MP_CRC1                           0x3198
#define mmISP_CORE_MI_MP_CRC2                           0x319C
#define mmISP_CORE_MI_MP_CRC3                           0x31A0
#define mmISP_CORE_MI_MP_CRC4                           0x31A4
#define mmISP_CORE_MI_MP_CRC5                           0x31A8
#define mmISP_CORE_MI_MP_CRC6                           0x31AC
#define mmISP_CORE_MI_MP_CRC7                           0x31B0


// Registers from MI_WR_VP block

#define mmISP_CORE_MI_VP_CTRL                           0x3400
#define mmISP_CORE_MI_VP_CTRL2                          0x3404
#define mmISP_CORE_MI_VP_INIT                           0x3408
#define mmISP_CORE_MI_VP_INIT2                          0x340C
#define mmISP_CORE_MI_VP_Y_BASE_AD_INIT                 0x3410
#define mmISP_CORE_MI_VP_Y_BASE_AD_H_INIT               0x3414
#define mmISP_CORE_MI_VP_Y_SIZE_INIT                    0x3418
#define mmISP_CORE_MI_VP_Y_IRQ_OFFS_INIT                0x341C
#define mmISP_CORE_MI_VP_Y_LLENGTH_INIT                 0x3420
#define mmISP_CORE_MI_VP_CB_BASE_AD_INIT                0x3424
#define mmISP_CORE_MI_VP_CB_BASE_AD_H_INIT              0x3428
#define mmISP_CORE_MI_VP_CB_SIZE_INIT                   0x342C
#define mmISP_CORE_MI_VP_CB_IRQ_OFFS_INIT               0x3430
#define mmISP_CORE_MI_VP_CB_LLENGTH_INIT                0x3434
#define mmISP_CORE_MI_VP_CR_BASE_AD_INIT                0x3438
#define mmISP_CORE_MI_VP_CR_BASE_AD_H_INIT              0x343C
#define mmISP_CORE_MI_VP_CR_SIZE_INIT                   0x3440
#define mmISP_CORE_MI_VP_CR_IRQ_OFFS_INIT               0x3444
#define mmISP_CORE_MI_VP_CR_LLENGTH_INIT                0x3448
#define mmISP_CORE_MI_VP_CTRL_SHD                       0x344C
#define mmISP_CORE_MI_VP_Y_BASE_AD_SHD                  0x3450
#define mmISP_CORE_MI_VP_Y_BASE_AD_H_SHD                0x3454
#define mmISP_CORE_MI_VP_Y_SIZE_SHD                     0x3458
#define mmISP_CORE_MI_VP_Y_IRQ_OFFS_SHD                 0x345C
#define mmISP_CORE_MI_VP_Y_LLENGTH_SHD                  0x3460
#define mmISP_CORE_MI_VP_CB_BASE_AD_SHD                 0x3464
#define mmISP_CORE_MI_VP_CB_BASE_AD_H_SHD               0x3468
#define mmISP_CORE_MI_VP_CB_SIZE_SHD                    0x346C
#define mmISP_CORE_MI_VP_CB_IRQ_OFFS_SHD                0x3470
#define mmISP_CORE_MI_VP_CB_LLENGTH_SHD                 0x3474
#define mmISP_CORE_MI_VP_CR_BASE_AD_SHD                 0x3478
#define mmISP_CORE_MI_VP_CR_BASE_AD_H_SHD               0x347C
#define mmISP_CORE_MI_VP_CR_SIZE_SHD                    0x3480
#define mmISP_CORE_MI_VP_CR_IRQ_OFFS_SHD                0x3484
#define mmISP_CORE_MI_VP_CR_LLENGTH_SHD                 0x3488
#define mmISP_CORE_MI_VP_IMSC                           0x348C
#define mmISP_CORE_MI_VP_RIS                            0x3490
#define mmISP_CORE_MI_VP_MIS                            0x3494
#define mmISP_CORE_MI_VP_ICR                            0x3498
#define mmISP_CORE_MI_VP_ISR                            0x349C
#define mmISP_CORE_MI_VP_STATUS                         0x34A0
#define mmISP_CORE_MI_VP_STATUS_CLR                     0x34A4
#define mmISP_CORE_MI_VP_RAW_BYTE_CNT                   0x34A8
#define mmISP_CORE_MI_VP_DP_PIXEL_CNT                   0x34AC
#define mmISP_CORE_MI_VP_MCH0_BYTE_CNT                  0x34B0
#define mmISP_CORE_MI_VP_MCH1_BYTE_CNT                  0x34B4
#define mmISP_CORE_MI_VP_MCH2_BYTE_CNT                  0x34B8
#define mmISP_CORE_MI_VP_PSTATE_CTRL_Y                  0x34C0
#define mmISP_CORE_MI_VP_PSTATE_CTRL_CB                 0x34C4
#define mmISP_CORE_MI_VP_PSTATE_CTRL_CR                 0x34C8
#define mmISP_CORE_MI_VP_PSTATE_ALLOW_STAT              0x34CC
#define mmISP_CORE_MI_VP_CID_ENABLE                     0x34D8
#define mmISP_CORE_MI_VP_LEAK_ENABLE                    0x34DC
#define mmISP_CORE_MI_VP_LEAK_TH_Y                      0x34E0
#define mmISP_CORE_MI_VP_LEAK_TH_CB                     0x34E4
#define mmISP_CORE_MI_VP_LEAK_TH_CR                     0x34E8
#define mmISP_CORE_MI_VP_TIMER_EN                       0x34EC
#define mmISP_CORE_MI_VP_TIMER_TH                       0x34F0
#define mmISP_CORE_MI_VP_CUR_LEAK_STATUS                0x34FC
#define mmISP_CORE_MI_VP_SRAM_FILL_LEVEL_Y              0x3500
#define mmISP_CORE_MI_VP_SRAM_FILL_LEVEL_CB             0x3504
#define mmISP_CORE_MI_VP_SRAM_FILL_LEVEL_CR             0x3508
#define mmISP_CORE_MI_VP_FIFO_OVERFLOW                  0x350C
#define mmISP_CORE_MI_VP_MAFD                           0x3520
#define mmISP_CORE_MI_VP_SPH_TEST                       0x3524
#define mmISP_CORE_MI_VP_SPH_WDATA                      0x3528
#define mmISP_CORE_MI_VP_STALL                          0x352C
#define mmISP_CORE_MI_VP_AXI_GENERAL                    0x3540
#define mmISP_CORE_MI_VP_AXI_AWUSER                     0x3544
#define mmISP_CORE_MI_VP_AXI_WUSER                      0x3548
#define mmISP_CORE_MI_VP_QOS_CTRL                       0x354C
#define mmISP_CORE_MI_VP_PFM_CTRL                       0x3550
#define mmISP_CORE_MI_VP_PFM_REGION_SET0                0x3554
#define mmISP_CORE_MI_VP_PFM_REGION_SET1                0x3558
#define mmISP_CORE_MI_VP_PFM_REGION_SET2                0x355C
#define mmISP_CORE_MI_VP_PFM_REGION_SET3                0x3560
#define mmISP_CORE_MI_VP_PFM_REGION_SET4                0x3564
#define mmISP_CORE_MI_VP_PFM_REGION_SET5                0x3568
#define mmISP_CORE_MI_VP_PFM_REGION_SET6                0x356C
#define mmISP_CORE_MI_VP_PFM_REGION_SET7                0x3570
#define mmISP_CORE_MI_VP_PFM_STAT_0_1_CNT               0x3574
#define mmISP_CORE_MI_VP_PFM_STAT_2_3_CNT               0x3578
#define mmISP_CORE_MI_VP_PFM_STAT_4_5_CNT               0x357C
#define mmISP_CORE_MI_VP_PFM_STAT_6_7_CNT               0x3580
#define mmISP_CORE_MI_VP_CTRL_CRC                       0x3590
#define mmISP_CORE_MI_VP_CRC0                           0x3594
#define mmISP_CORE_MI_VP_CRC1                           0x3598
#define mmISP_CORE_MI_VP_CRC2                           0x359C
#define mmISP_CORE_MI_VP_CRC3                           0x35A0
#define mmISP_CORE_MI_VP_CRC4                           0x35A4
#define mmISP_CORE_MI_VP_CRC5                           0x35A8
#define mmISP_CORE_MI_VP_CRC6                           0x35AC
#define mmISP_CORE_MI_VP_CRC7                           0x35B0


// Registers from MI_WR_PP block

#define mmISP_CORE_MI_PP_CTRL                           0x3800
#define mmISP_CORE_MI_PP_CTRL2                          0x3804
#define mmISP_CORE_MI_PP_INIT                           0x3808
#define mmISP_CORE_MI_PP_INIT2                          0x380C
#define mmISP_CORE_MI_PP_Y_BASE_AD_INIT                 0x3810
#define mmISP_CORE_MI_PP_Y_BASE_AD_H_INIT               0x3814
#define mmISP_CORE_MI_PP_Y_SIZE_INIT                    0x3818
#define mmISP_CORE_MI_PP_Y_IRQ_OFFS_INIT                0x381C
#define mmISP_CORE_MI_PP_Y_LLENGTH_INIT                 0x3820
#define mmISP_CORE_MI_PP_CB_BASE_AD_INIT                0x3824
#define mmISP_CORE_MI_PP_CB_BASE_AD_H_INIT              0x3828
#define mmISP_CORE_MI_PP_CB_SIZE_INIT                   0x382C
#define mmISP_CORE_MI_PP_CB_IRQ_OFFS_INIT               0x3830
#define mmISP_CORE_MI_PP_CB_LLENGTH_INIT                0x3834
#define mmISP_CORE_MI_PP_CR_BASE_AD_INIT                0x3838
#define mmISP_CORE_MI_PP_CR_BASE_AD_H_INIT              0x383C
#define mmISP_CORE_MI_PP_CR_SIZE_INIT                   0x3840
#define mmISP_CORE_MI_PP_CR_IRQ_OFFS_INIT               0x3844
#define mmISP_CORE_MI_PP_CR_LLENGTH_INIT                0x3848
#define mmISP_CORE_MI_PP_CTRL_SHD                       0x384C
#define mmISP_CORE_MI_PP_Y_BASE_AD_SHD                  0x3850
#define mmISP_CORE_MI_PP_Y_BASE_AD_H_SHD                0x3854
#define mmISP_CORE_MI_PP_Y_SIZE_SHD                     0x3858
#define mmISP_CORE_MI_PP_Y_IRQ_OFFS_SHD                 0x385C
#define mmISP_CORE_MI_PP_Y_LLENGTH_SHD                  0x3860
#define mmISP_CORE_MI_PP_CB_BASE_AD_SHD                 0x3864
#define mmISP_CORE_MI_PP_CB_BASE_AD_H_SHD               0x3868
#define mmISP_CORE_MI_PP_CB_SIZE_SHD                    0x386C
#define mmISP_CORE_MI_PP_CB_IRQ_OFFS_SHD                0x3870
#define mmISP_CORE_MI_PP_CB_LLENGTH_SHD                 0x3874
#define mmISP_CORE_MI_PP_CR_BASE_AD_SHD                 0x3878
#define mmISP_CORE_MI_PP_CR_BASE_AD_H_SHD               0x387C
#define mmISP_CORE_MI_PP_CR_SIZE_SHD                    0x3880
#define mmISP_CORE_MI_PP_CR_IRQ_OFFS_SHD                0x3884
#define mmISP_CORE_MI_PP_CR_LLENGTH_SHD                 0x3888
#define mmISP_CORE_MI_PP_IMSC                           0x388C
#define mmISP_CORE_MI_PP_RIS                            0x3890
#define mmISP_CORE_MI_PP_MIS                            0x3894
#define mmISP_CORE_MI_PP_ICR                            0x3898
#define mmISP_CORE_MI_PP_ISR                            0x389C
#define mmISP_CORE_MI_PP_STATUS                         0x38A0
#define mmISP_CORE_MI_PP_STATUS_CLR                     0x38A4
#define mmISP_CORE_MI_PP_RAW_BYTE_CNT                   0x38A8
#define mmISP_CORE_MI_PP_DP_PIXEL_CNT                   0x38AC
#define mmISP_CORE_MI_PP_MCH0_BYTE_CNT                  0x38B0
#define mmISP_CORE_MI_PP_MCH1_BYTE_CNT                  0x38B4
#define mmISP_CORE_MI_PP_MCH2_BYTE_CNT                  0x38B8
#define mmISP_CORE_MI_PP_PSTATE_CTRL_Y                  0x38C0
#define mmISP_CORE_MI_PP_PSTATE_CTRL_CB                 0x38C4
#define mmISP_CORE_MI_PP_PSTATE_CTRL_CR                 0x38C8
#define mmISP_CORE_MI_PP_PSTATE_ALLOW_STAT              0x38CC
#define mmISP_CORE_MI_PP_CID_ENABLE                     0x38D8
#define mmISP_CORE_MI_PP_LEAK_ENABLE                    0x38DC
#define mmISP_CORE_MI_PP_LEAK_TH_Y                      0x38E0
#define mmISP_CORE_MI_PP_LEAK_TH_CB                     0x38E4
#define mmISP_CORE_MI_PP_LEAK_TH_CR                     0x38E8
#define mmISP_CORE_MI_PP_TIMER_EN                       0x38EC
#define mmISP_CORE_MI_PP_TIMER_TH                       0x38F0
#define mmISP_CORE_MI_PP_CUR_LEAK_STATUS                0x38FC
#define mmISP_CORE_MI_PP_SRAM_FILL_LEVEL_Y              0x3900
#define mmISP_CORE_MI_PP_SRAM_FILL_LEVEL_CB             0x3904
#define mmISP_CORE_MI_PP_SRAM_FILL_LEVEL_CR             0x3908
#define mmISP_CORE_MI_PP_FIFO_OVERFLOW                  0x390C
#define mmISP_CORE_MI_PP_MAFD                           0x3920
#define mmISP_CORE_MI_PP_SPH_TEST                       0x3924
#define mmISP_CORE_MI_PP_SPH_WDATA                      0x3928
#define mmISP_CORE_MI_PP_STALL                          0x392C
#define mmISP_CORE_MI_PP_AXI_GENERAL                    0x3940
#define mmISP_CORE_MI_PP_AXI_AWUSER                     0x3944
#define mmISP_CORE_MI_PP_AXI_WUSER                      0x3948
#define mmISP_CORE_MI_PP_QOS_CTRL                       0x394C
#define mmISP_CORE_MI_PP_PFM_CTRL                       0x3950
#define mmISP_CORE_MI_PP_PFM_REGION_SET0                0x3954
#define mmISP_CORE_MI_PP_PFM_REGION_SET1                0x3958
#define mmISP_CORE_MI_PP_PFM_REGION_SET2                0x395C
#define mmISP_CORE_MI_PP_PFM_REGION_SET3                0x3960
#define mmISP_CORE_MI_PP_PFM_REGION_SET4                0x3964
#define mmISP_CORE_MI_PP_PFM_REGION_SET5                0x3968
#define mmISP_CORE_MI_PP_PFM_REGION_SET6                0x396C
#define mmISP_CORE_MI_PP_PFM_REGION_SET7                0x3970
#define mmISP_CORE_MI_PP_PFM_STAT_0_1_CNT               0x3974
#define mmISP_CORE_MI_PP_PFM_STAT_2_3_CNT               0x3978
#define mmISP_CORE_MI_PP_PFM_STAT_4_5_CNT               0x397C
#define mmISP_CORE_MI_PP_PFM_STAT_6_7_CNT               0x3980
#define mmISP_CORE_MI_PP_CTRL_CRC                       0x3990
#define mmISP_CORE_MI_PP_CRC0                           0x3994
#define mmISP_CORE_MI_PP_CRC1                           0x3998
#define mmISP_CORE_MI_PP_CRC2                           0x399C
#define mmISP_CORE_MI_PP_CRC3                           0x39A0
#define mmISP_CORE_MI_PP_CRC4                           0x39A4
#define mmISP_CORE_MI_PP_CRC5                           0x39A8
#define mmISP_CORE_MI_PP_CRC6                           0x39AC
#define mmISP_CORE_MI_PP_CRC7                           0x39B0


// Registers from MI_RD block

#define mmISP_CORE_MI_RD_DMA_Y_PIC_START_AD_INIT        0x3C00
#define mmISP_CORE_MI_RD_DMA_Y_PIC_START_AD_H_INIT      0x3C04
#define mmISP_CORE_MI_RD_DMA_Y_PIC_WIDTH_INIT           0x3C08
#define mmISP_CORE_MI_RD_DMA_Y_LLENGTH_INIT             0x3C0C
#define mmISP_CORE_MI_RD_DMA_Y_PIC_SIZE_INIT            0x3C10
#define mmISP_CORE_MI_RD_DMA_Y_PIC_START_AD_SHD         0x3C34
#define mmISP_CORE_MI_RD_DMA_Y_PIC_START_AD_H_SHD       0x3C38
#define mmISP_CORE_MI_RD_DMA_Y_PIC_WIDTH_SHD            0x3C3C
#define mmISP_CORE_MI_RD_DMA_Y_LLENGTH_SHD              0x3C40
#define mmISP_CORE_MI_RD_DMA_Y_PIC_SIZE_SHD             0x3C44
#define mmISP_CORE_MI_RD_DMA_CTRL                       0x3C68
#define mmISP_CORE_MI_RD_DMA_INIT                       0x3C6C
#define mmISP_CORE_MI_RD_DMA_AUTO_CFG_UPDATE            0x3C70
#define mmISP_CORE_MI_RD_DMA_GEN_CFG_UPDATE             0x3C74
#define mmISP_CORE_MI_RD_DMA_START                      0x3C78
#define mmISP_CORE_MI_RD_DMA_STATUS                     0x3C7C
#define mmISP_CORE_MI_RD_IMSC                           0x3C80
#define mmISP_CORE_MI_RD_RIS                            0x3C84
#define mmISP_CORE_MI_RD_MIS                            0x3C88
#define mmISP_CORE_MI_RD_ICR                            0x3C8C
#define mmISP_CORE_MI_RD_ISR                            0x3C90
#define mmISP_CORE_MI_RD_DMA_STALL                      0x3C94
#define mmISP_CORE_MI_RD_DMA_TIMER_EN                   0x3C98
#define mmISP_CORE_MI_RD_DMA_TIMER_TH                   0x3C9C
#define mmISP_CORE_MI_RD_AXI_ARUSER                     0x3CA0
#define mmISP_CORE_MI_RD_QOS_CTRL                       0x3CA4
#define mmISP_CORE_MI_RD_MAFD                           0x3CA8
#define mmISP_CORE_MI_RD_AXI_GENERAL                    0x3CAC
#define mmISP_CORE_MI_RD_PFM_CTRL                       0x3CB0
#define mmISP_CORE_MI_RD_PFM_REGION_SET0                0x3CB4
#define mmISP_CORE_MI_RD_PFM_REGION_SET1                0x3CB8
#define mmISP_CORE_MI_RD_PFM_REGION_SET2                0x3CBC
#define mmISP_CORE_MI_RD_PFM_REGION_SET3                0x3CC0
#define mmISP_CORE_MI_RD_PFM_REGION_SET4                0x3CC4
#define mmISP_CORE_MI_RD_PFM_REGION_SET5                0x3CC8
#define mmISP_CORE_MI_RD_PFM_REGION_SET6                0x3CCC
#define mmISP_CORE_MI_RD_PFM_REGION_SET7                0x3CD0
#define mmISP_CORE_MI_RD_PFM_STAT_0_1_CNT               0x3CD4
#define mmISP_CORE_MI_RD_PFM_STAT_2_3_CNT               0x3CD8
#define mmISP_CORE_MI_RD_PFM_STAT_4_5_CNT               0x3CDC
#define mmISP_CORE_MI_RD_PFM_STAT_6_7_CNT               0x3CE0



#endif
