INC_LIB_DIR += -I$(LVGL_DIR)/lvgl/porting

PUBLIC_LIB_H +=  $(LVGL_DIR)/lvgl/porting/lv_port_disp.h
PUBLIC_LIB_H +=  $(LVGL_DIR)/lvgl/porting/lv_port_indev.h

SOURCE_LIB_C +=  $(LVGL_DIR)/lvgl/porting/lv_port_disp.c 
SOURCE_LIB_C +=  $(LVGL_DIR)/lvgl/porting/lv_port_indev.c
