INC_LIB_DIR  += -I$(SDK_ROOT)/components/drivers/usb2otg/functions/uvc_bulk

SOURCE_LIB_C += $(SDK_ROOT)/components/drivers/usb2otg/functions/uvc_bulk/uvc_bulk.c
SOURCE_LIB_C += $(SDK_ROOT)/components/drivers/usb2otg/functions/uvc_bulk/uvc_bulk_ep0.c
