#Include C Source Files
SOURCE_LIB_C += $(SDK_ROOT)/components/gui/UGUI/ugui.c
INC_LIB_DIR  += -I$(SDK_ROOT)/components/gui/UGUI

ifeq ($(CONFIG_GUI_USE_LVGL),y)
-include $(SDK_ROOT)/components/gui/LVGL-v8.3.9_Src/Makefile
endif




