SOURCE_LIB_C += $(wildcard $(LVGL_DIR)/lvgl/src/*/*.c)
SOURCE_LIB_C += $(wildcard $(LVGL_DIR)/lvgl/src/*/*/*.c)
SOURCE_LIB_C += $(wildcard $(LVGL_DIR)/lvgl/src/*/*/*/*.c)

PUBLIC_LIB_H +=  $(LVGL_DIR)/lvgl/src/*.h
PUBLIC_LIB_H +=  $(LVGL_DIR)/lvgl/src/*/*.h
PUBLIC_LIB_H +=  $(LVGL_DIR)/lvgl/src/*/*/*.h
PUBLIC_LIB_H +=  $(LVGL_DIR)/lvgl/src/*/*/*/*.h