ifeq ($(CONFIG_USB_SINK_LPBK),y)
-include $(SDK_ROOT)/components/drivers/usb2otg/functions/usb_sink_lpbk/Makefile
endif

ifeq ($(CONFIG_UVC_CAMERA),y)
-include $(SDK_ROOT)/components/drivers/usb2otg/functions/uvc_camera/Makefile
endif

