#ifndef _ISPHW_REG_BASE_H_
#define _ISPHW_REG_BASE_H_

#include "isp_hal.h"

#ifdef __cplusplus
extern "C"
{
#endif

//--WDMA REG
#define WDMA1_REG_BASE (mmISP_CORE_MI_PP_CTRL)
#define WDMA2_REG_BASE (mmISP_CORE_MI_VP_CTRL)
#define WDMA3_REG_BASE (mmISP_CORE_MI_MP_CTRL)

//--RESIZE REG
#define RESIZE1_REG_BASE (mmISP_CORE_PRSZ_CTRL)
#define RESIZE2_REG_BASE (mmISP_CORE_VRSZ_CTRL)
#define RESIZE3_REG_BASE (mmISP_CORE_MRSZ_CTRL)

//--ISP Kernel DEGAMMA
#define ISP_DEGAMMA_CURVE_R_REG_BASE (mmISP_CORE_ISP_GAMMA_R_Y_0)
#define ISP_DEGAMMA_CURVE_G_REG_BASE (mmISP_CORE_ISP_GAMMA_G_Y_0)
#define ISP_DEGAMMA_CURVE_B_REG_BASE (mmISP_CORE_ISP_GAMMA_B_Y_0)


//--PREP DEGAMMA
#define PREP_DEGAMMA_CURVE_R_REG_BASE (mmISP_CORE_PREP_GAMMA_R_Y_0)
#define PREP_DEGAMMA_CURVE_G_REG_BASE (mmISP_CORE_PREP_GAMMA_G_Y_0)
#define PREP_DEGAMMA_CURVE_B_REG_BASE (mmISP_CORE_PREP_GAMMA_B_Y_0)

    
//--BNR NLL COEFF
#define BNR_NLL_COEFF_REG_BASE (mmISP_CORE_ISP_BNR_NLL_COEFF_0)

//--HIST BIN
#define HIST_BIN_REG_BASE (mmISP_CORE_ISP_HIST_BIN_0)
    
//--GAMMA OUT
//Define the gamma out curve base address
#define GAMMA_OUT_CURVE_REG_BASE (mmISP_CORE_ISP_GAMMA_OUT_Y_0)

//--WDR YM
#define WDR_TONECURVE_YM_REG_BASE (mmISP_CORE_ISP_WDR_TONECURVE_YM_0)


#ifdef __cplusplus
}
#endif



#endif
