INC_LIB_DIR  += -I$(SDK_ROOT)/components/drivers/videoin/device

ifeq ($(CONFIG_MIPI_CIS_GC1054),y)
SOURCE_LIB_C += $(SDK_ROOT)/components/drivers/videoin/device/cis_gc1054.c
endif

ifeq ($(CONFIG_MIPI_CIS_OG0VA1B),y)
SOURCE_LIB_C += $(SDK_ROOT)/components/drivers/videoin/device/cis_og0va1b.c
endif

ifeq ($(CONFIG_MIPI_CIS_OG01A1B),y)
SOURCE_LIB_C += $(SDK_ROOT)/components/drivers/videoin/device/cis_og01a1b.c
endif

ifeq ($(CONFIG_MIPI_CIS_OV02K10),y)
SOURCE_LIB_C += $(SDK_ROOT)/components/drivers/videoin/device/cis_ov02k10.c
endif

ifeq ($(CONFIG_MIPI_CIS_OV02K10_HDR),y)
SOURCE_LIB_C += $(SDK_ROOT)/components/drivers/videoin/device/cis_ov02k10_hdr.c
endif

ifeq ($(CONFIG_MIPI_CIS_SC132GS),y)
SOURCE_LIB_C += $(SDK_ROOT)/components/drivers/videoin/device/cis_sc132gs.c
endif

ifeq ($(CONFIG_MIPI_CIS_SC132GS_HDR),y)
SOURCE_LIB_C += $(SDK_ROOT)/components/drivers/videoin/device/cis_sc132gs_hdr.c
endif

ifeq ($(CONFIG_DVPI_CIS_OV7725),y)
SOURCE_LIB_C += $(SDK_ROOT)/components/drivers/videoin/device/cis_ov7725dvpi.c
endif

ifeq ($(CONFIG_MIPI_CIS_GC2053),y)
SOURCE_LIB_C += $(SDK_ROOT)/components/drivers/videoin/device/cis_gc2053.c
endif

ifeq ($(CONFIG_MIPI_CIS_SC200),y)
SOURCE_LIB_C += $(SDK_ROOT)/components/drivers/videoin/device/cis_sc200.c
endif